#!/bin/bash
# shell script to generate cross-section splines (in .xml format)
# and convert to root file
# make sure to do: 
# 0. start a new spline session (screen -S spline)
# 1. source genie_env.sh
# 2. run this script the directory that contains Generator/ and Reweight/
# since the genie_env.sh will look for those directories
# 3. while running (gmkspl might take 24-48 hrs), cntrl + A + D to put on background, and potentially run another process in parallel

target=$1   # user command-line input input (D2, C12, Ar40, Ca40, Ca48
base_name="${target}_spline_G18_10a_02_11a"  # input/output files base name
beam_pdg="11"         # incident particle code (11 for electron)
Eb_max="11"           # upper limit on beam energy GeV
Eb="5.98636"          # actual beam energy


tgt_pdg_d2="1000010020"    # target pdg code
tgt_pdg_c12="1000060120"   # target pdg code
tgt_pdg_ar40="1000180400"  
nevts="50000"       # total number of events generated
tune="G18_10a_02_11a" # GENIE tune 

# Set Target PDG codes
if [ "${target}" = "d2" ]; then
    tgt_pdg=${tgt_pdg_d2}
    echo "Target Used: ${target} (PDG CODE: ${tgt_pdg})"
elif  [ "${target}" = "c12" ]; then
    tgt_pdg=${tgt_pdg_c12}
    echo "Target Used: ${target} (PDG CODE: ${tgt_pdg})"
elif [ "${target}" = "ar40" ]; then
    tgt_pdg=${tgt_pdg_ar40}
    echo "Target Used: ${target} (PDG CODE: ${tgt_pdg})"
else	
    echo "Please enter a target type: d2, c12, ar40"
fi

# GENIE input flags information (see p. 105 of https://genie-docdb.pp.rl.ac.uk/DocDB/0000/000002/007/man.pdf)

# See PDG particle  codes: https://root.cern.ch/doc/master/TDatabasePDG_8cxx_source.html
# See Monte-Carlo Numbering Scheme: https://pdg.lbl.gov/2007/reviews/montecarlorpp.pdf
# See Numbering Scheme paper: https://arxiv.org/pdf/1812.05616.pdf

#====================
# gmkspl input flags
# (utility to write-out cross-section
# values in .XML format)
#====================
# -p : specifies incident particle PDG code,  for example incident electron will be: -p 11

# -t : specifies target PDG code (using PDG2006 conventions 10LZZZAAAI)
# L: strange number (0 for stable nuclei), ZZZ: 3-digit atomic number, AAA: 3-digit mass number, I: isomer number (0 for ground-state nuclei)
# Relevant targets for RGM:
#      Hydrogen (1H) :       L ZZZ AAA I
#      Deuteron (2H) : -t 10 0 001 002 0
#      Helium-4      : -t 10 0 002 004 0
#      Carbon-12     : -t 10 0 006 012 0
#      Calcium-40    : -t 10 0 020 040 0
#      Calcium-48    : -t 10 0 020 048 0
#      Argon-40      : -t 10 0 018 040 0   
#      Sn-120        : -t 10 0 050 120 0

# -e : specifies the maximum (OR UPPER LIMIT) incident "beam" energy in the range of each spline (GeV)

# -n : Specified the number of knots per spline (J. Barrow recommends 100 - 250 knots
#      the more knots, the more "accuracy" (in terms of how the model is evaluated

# -o : specifies the name of an outpout cross-section XML file (if not specified, GENIE writes-out 'xsec_splines.xml'

# --tune : specifies which tune to use (recommended by Afro is tune: G18_10a_02_11a)

# --event-generator-list : list of event generators to load, (since I want to simulate electro-nuclear interactions, I assume EM is sufficient)
#                          to show how all of the other background that contributes to your supposed signal, an event-generator-list should NOT be used       

# Since RGM highest beam energy was 5.98 GeV,  I would think setting an upper limit of: ~ 6 GeV will be OK, or is it better to go up to 11 GeV )??


# generate pion electro production off deuterium: d(e,e'pi)  with incident e- beam energy of 5.98
#cmd_xml="gmkspl -p ${beam_pdg} -t ${tgt_pdg} -e ${Eb_max} -o ${base_name}.xml --tune ${tune} --event-generator-list EM"
#echo "Executing ----> ${cmd_xml}"
#eval ${cmd_xml}

# The output cross sections on d(e,e') will range up to beam energies Eb_max and will be in .xml format (in the next step, the user can specify which beam energy Eb to use)

#=========================
# gevgen input flags
# (generic GENIE event
# generation application)
#=========================

# flags

# -n : specifies number of events to generate
# -p : specifies incident particle PDG code, for example for electrons, -p 11
# -t : specifies target PDG codes (see notes above)
# -e : specifies incident energy or energy range  (Im assuming in this case, I should enter the exact beam energy, for example, -e 5.98636, corresponding to part of the RGM data)
#      or is it suggested I specify a range of energies??? (which accoring to docs, I would have to specify a neutrino (I guess electrons in my case) flux spectrum.
# --event-generator-list : see gmkspl flags above
# --tune : see gmkspl flags above
# --cross-sections : specify the name of the input XML file ( should have been generated by the gmkspl command already )

#cmd_gen="gevgen -n ${nevts} -p ${beam_pdg} -t ${tgt_pdg} -e ${Eb} --tune ${tune} --event-generator-list EM --cross-sections ${base_name}.xml -o ${base_name}.ghep.root" 
#echo "Executing ----> ${cmd_gen}"
#eval ${cmd_gen}
# the output will be a GEHEP file of the form: ${base_name}, with cross sections which must then be converted to a ROOT file

#==================================
# gntpc input flags
# (utility to convert the native
# GENIE GHEP event file to either
# plain text, XML or .root )
#==================================

# -f : specifies the output format, where 'gst' is a GENIE summary ntuple format that can be used for plotting with ROOT
# -i : specifies the output file name

#cmd_gntpc="gntpc -f gst -i ${base_name}.ghep.root -o ${base_name}.root"
#echo "Executing ----> ${cmd_gntpc}"
#eval ${cmd_gntpc}
