#! bin/bash

# shell script to generate cross-section splines (in .xml format)
# and convert to root file

# input flags information (see p. 105 of https://genie-docdb.pp.rl.ac.uk/DocDB/0000/000002/007/man.pdf)

# See PDG particle  codes: https://root.cern.ch/doc/master/TDatabasePDG_8cxx_source.html
# See Monte-Carlo Numbering Scheme: https://pdg.lbl.gov/2007/reviews/montecarlorpp.pdf
# See Numbering Scheme paper: https://arxiv.org/pdf/1812.05616.pdf

#====================
# gmkspl input flags
# (utility to write-out cross-section
# values in .XML format)
#====================
# -p : specifies incident particle PDG code,  for example incident electron will be: -p 11

# -t : specifies target PDG code (using PDG2006 conventions 10LZZZAAAI)
# L: strange number (0 for stable nuclei), ZZZ: 3-digit atomic number, AAA: 3-digit mass number, I: isomer number (0 for ground-state nuclei)
# Relevant targets for RGM:
#      Hydrogen (1H) :       L ZZZ AAA I
#      Deuteron (2H) : -t 10 0 001 002 0
#      Helium-4      : -t 10 0 002 004 0
#      Carbon-12     : -t 10 0 006 012 0
#      Calcium-40    : -t 10 0 020 040 0
#      Calcium-48    : -t 10 0 020 048 0
#      Argon-40      : -t 10 0 018 040 0   
#      Sn-120        : -t 10 0 050 120 0

# -e : specifies the maximum (OR UPPER LIMIT) incident "beam" energy in the range of each spline (GeV)

# -n : Specified the number of knots per spline (J. Barrow recommends 100 - 250 knots
#      the more knots, the more "accuracy" (in terms of how the model is evaluated

# -o : specifies the name of an outpout cross-section XML file (if not specified, GENIE writes-out 'xsec_splines.xml'

# --tune : specifies which tune to use (recommended by Afro is tune: G18_10a_02_11a)

# --event-generator-list : list of event generators to load, (since I want to simulate electro-nuclear interactions, I assume EM is sufficient)



# Since RGM highest beam energy was 5.98 GeV,  I would think setting an upper limit of: ~ 6 GeV will be OK, or is it better to go up to 11 GeV )??


# generate pion electro production off deuterium: d(e,e'pi)  with incident e- beam energy of 5.98
cmd_xml="gmkspl -p 11 -t 1000010020 -e 11 -n 250 -o deepi_spline_EM_G18_10a_02_11a.xml --tune G18_10a_02_11a --event-generator-list EM"

#=========================
# gevgen input flags
# (generic GENIE event
# generation application)
#=========================

# flags

# -n : specifies number of events to generate
# -p : specifies incident particle PDG code, for example for electrons, -p 11
# -t : specifies target PDG codes (see notes above)
# -e : specifies incident energy or energy range  (Im assuming in this case, I should enter the exact beam energy, for example, -e 5.98636, corresponding to part of the RGM data)
#      or is it suggested I specify a range of energies??? (which accoring to docs, I would have to specify a neutrino (I guess electrons in my case) flux spectrum.
# --event-generator-list : see gmkspl flags above
# --tune : see gmkspl flags above
# --cross-sections : specify the name of the input XML file ( should have been generated by the gmkspl command already )
cmd_gen="gevgen -n 10 -p 11 -t 1000010020 -e 5.98636  --event-generator-list EM --tune G18_10a_02_11a --cross-sections deepi_spline_EM_G18_10a_02_11a.xml" 

# the output will be a GEHEP file, which must then be converted to a ROOT file

#==================================
# gntpc input flags
# (utility to convert the native
# GENIE GHEP event file to either
# plain text, XML or .root )
#==================================

# -f : specifies the output format, where 'gst' is a GENIE summary ntuple format that can be used for plotting with ROOT
# -i : specifies the output file name

cmd_gntpc="gntpc -f gst -i deepi_spline_EM_G18_10a_02_11a.root"
